name: RalphMobile

options:
  bundleIdPrefix: dev.ralph
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  localPackagesGroup: Packages

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    TARGETED_DEVICE_FAMILY: "1,2"

packages:
  RalphShared:
    path: ../packages/RalphShared
  Citadel:
    url: https://github.com/orlandos-nl/Citadel
    from: "0.12.0"

targets:
  RalphMobile:
    type: application
    platform: iOS
    sources:
      - path: RalphMobile
        createIntermediateGroups: true
        excludes:
          - "**/.DS_Store"
          - "**/*.md"
    dependencies:
      - package: RalphShared
      - package: Citadel
    info:
      path: RalphMobile/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleURLTypes:
          - CFBundleURLName: dev.ralph.RalphMobile
            CFBundleURLSchemes:
              - ralph
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.ralph.RalphMobile
        INFOPLIST_FILE: RalphMobile/Info.plist
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    preBuildScripts:
      - name: Start Backend
        script: |
          if [ "${CONFIGURATION}" = "Debug" ]; then
            "${SRCROOT}/scripts/xcode-prebuild.sh" &
          fi
        basedOnDependencyAnalysis: false
    scheme:
      testTargets:
        - RalphMobileTests
        - RalphMobileUITests

  RalphMobileTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RalphMobileTests
        excludes:
          - "**/*.md"
    dependencies:
      - target: RalphMobile
      - package: RalphShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.ralph.RalphMobileTests

  RalphMobileUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: RalphMobileUITests
        excludes:
          - "**/*.md"
    dependencies:
      - target: RalphMobile
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.ralph.RalphMobileUITests

schemes:
  RalphMobile:
    build:
      targets:
        RalphMobile: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - RalphMobileTests
        - RalphMobileUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
